name: Deploy Next.js 15 App to FastComet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Lint Check (ESLint)
        run: npm run lint

      - name: Run Prettier Check
        run: npm run format --check

      - name: Run Jest Tests
        run: npm test

      - name: Build Next.js App
        run: npm run build

      - name: Deploy to Vercel
        if: success()  # ✅ Deploy only if all previous steps pass
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
